name: baby build

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # runs exactly at 00:00, 06:00, 12:00, and 18:00 UTC
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Display current date and time
        run: date  # Helps in debugging if the workflow is running

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
