# File: .github/workflows/heartbeat.yml
name: Heartbeat

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  baby-build:
    runs-on: ubuntu-latest
    steps:
      - name: Show time
        run: echo "Workflow ran at $(date)"
